name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ prod ]
  schedule:
    # Runs every 6 hours, starting at 3am
    - cron: '0 3/6 * * *'
  workflow_dispatch:

jobs:
  lint:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint -- --max-warnings 0

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint -- --max-warnings 0
    - name: Build project
      run: npm run build

  update-stats:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Call stats endpoint to update history
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://prod.de8atwnp0x7a3.amplifyapp.com/api/cron
